# Generated by Django 3.2.3 on 2022-03-30 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20220330_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='forum',
            new_name='ad',
        ),
    ]
